---
# We want to be able to rebuild nginx-with-rtmp regularly via cron (so we ge
# the effect of unattended-upgrades). Simplest way to do that is to run the 
# build tasks as a local playback on the target host. So we install ansible on
# the host, copy the playbook, and set up cron to trigger it regularly.
- block:
  - name: Install pip
    apt: pkg={{item}} state=present
    with_items:
     - python-pip
     - libffi-dev
     - libssl-dev
     - python-dev

  - name: Install ansible
    pip: name={{item}} state=latest
    with_items:
     - paramiko
     - PyYAML
     - Jinja2
     - httplib2
     - six
     - markupsafe
     - cryptography
     - ansible

  - name: Copy playbook into place
    copy: src=nginx-rtmp-playbook.yml dest=/root/nginx-rtmp-playbook.yml
    tags: nginx-with-rtmp-build

  - name: Run playbook to build nginx-with-rtmp
    command: ansible-playbook -i "localhost," /root/nginx-rtmp-playbook.yml
    tags: nginx-with-rtmp-build

  - name: Install nginx-with-rtmp rebuilding cron
    cron: >
      name="Rebuild nginx-with-rtmp if needed"
      day="*" hour="6" minute="0"
      job="ansible-playbook -i 'localhost,' /root/nginx-rtmp-playbook.yml > /dev/null"

  tags: ['nginx-with-rtmp']
