---
- hosts: plenary
  become: yes
  become_user: root
  gather_facts: true
  vars_files:
    - vars/secrets.yml
  roles:
    - common
    - mosh
    - swap
    - nginx-with-rtmp
    - letsencrypt-nginx
    - letsencrypt
    - role: nodesource.node
      tags: ['node']
      nodejs_version: "6"
      debian_repo_version: "6.x"
    - monitored
    #- tarsnap
    - freeswitch
    - coturn
    - plenary
  vars:
    domain: "nothangout.media.mit.edu"
    plenary_domain: "plenary.unhangout.io"
    freeswitch_domain: "{{plenary_domain}}"
    coturn_domain: "{{plenary_domain}}"
    letsencrypt_domains:
      - "{{domain}}"
      - "{{plenary_domain}}"
