- block:
  # Verto communicator
  - name: Install grunt, bower
    npm: name={{item}} state=present global=yes
    with_items: ['grunt', 'grunt-cli', 'bower']

  - name: Install verto npm dependencies
    npm: path={{plenary_verto_dir}}

  - name: Install verto bower dependencies
    bower: path={{plenary_verto_dir}}
    
  - name: Run grunt task
    command: grunt build --force chdir={{plenary_verto_dir}}

